---
listen: localhost:8080

relays:
- wss://relay.example1.com
- wss://relay.example2.com

nip_11:
  name: blyat
  description: Your relays, OUR RELAYS
  software: git+https://github.com/Yonle/blyat
  pubkey: 0000000000000000000000000000000000000000000000000000000000000000
  contact: unset
  supported_nips:
  - 1
  - 2
  - 9
  - 11
  - 12
  - 15
  - 16
  - 20
  - 22
  - 33
  - 40
