---
listen: localhost:8080

favicon:

relays:
- wss://relay.example1.com
- wss://relay.example2.com

nip_11:
  name: bostr2
  description: Nostr relay bouncer
  software: git+https://github.com/Yonle/bostr2
  pubkey: 0000000000000000000000000000000000000000000000000000000000000000
  contact: unset
  supported_nips:
  - 1
  - 2
  - 9
  - 11
  - 12
  - 15
  - 16
  - 20
  - 22
  - 33
  - 40
  - 50
